### ISSUE TITLE
échanger "évènements" et "about" 

### ISSUE THREAD

**Issue by laurentperrinet** [CONECT-INT/CONECT-INT_website#5]
@MatthieuGilson suggère:

>  sur la page d'accueil de CONECT, il y a actuellement les posts de blog et il n'y en a pas de récent, au contraire des évènements... est-ce qu'il serait judicieux d'échanger ou de mettre un lien vers les évènements en gros (et aussi sur le doc partagé que tu as fait où on recense les envies de formation coding club CONECT) pour attirer les gens vers là où ça bouge ?

**Comment by laurentperrinet** [comment]
très bonne idée!

ce que tu suggères en fait, c'est de mettre les événements dans la page d'accueil de https://conect-int.github.io ...

**Comment by laurentperrinet** [comment]
j'ai fait ça dans le fichier `config/_default/menus.yaml` cf https://github.com/CONECT-INT/CONECT-INT_website/commit/44561a55807f09b6dd056591567d3f6fa1ee5f0d 

dites moi ce que vous pensez du résultat 👍 ou 👎 ?

**Comment by laurentperrinet** [comment]
ah ben non, c'est dans `content/home/news.md` cf. https://github.com/CONECT-INT/CONECT-INT_website/commit/23eccb0d511d452d36e45a25dca1c8dea22ea8ce 

c'est facile à oublier 🙄 
c'est pour ça que les issues sont pratiques 👍

**Comment by MatthieuGilson** [comment]
:+1: pour le changement de contenu, mais les photos/images sont un peu grosses pour la page d'accueil sur mon nav firefox

**Comment by laurentperrinet** [comment]
> 👍 pour le changement de contenu, mais les photos/images sont un peu grosses pour la page d'accueil sur mon nav firefox

ok, found something in https://wowchemy.com/blocks-v1/collection/#widget-specific-options see https://github.com/CONECT-INT/CONECT-INT_website/commit/77078b6bd34b63ecb2cd352b0dea40b788679137#diff-9b5bec8d9f5bc8b694006c46382ae0ead801bfe2020b5e279c4b6e5154444942

**Comment by laurentperrinet** [comment]
and the result is: 
<img width="666" alt="image" src="https://github.com/CONECT-INT/CONECT-INT_website/assets/381808/39ec1f38-9265-432e-a3af-98575ff8984e">

**Comment by MatthieuGilson** [comment]
:+1::+1:
